const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "1.25rem 0 3.125rem",
        display: "flex",
    },
    content: {
        background: "#fff",
        boxShadow: "0 1px 2px 0 rgb(0 0 0 / 13%)",
        borderRadius: ".125rem",
        marginLeft: "1.6875rem",
        padding: "0 1.875rem .625rem",
        width: "980px",
    },
    header: {
        borderBottom: ".0625rem solid #efefef",
        padding: "1.125rem 0",
        height: "80px",
        boxSizing: "border-box",
        alignItems: "center",
        display: "flex",
        justifyContent: "space-between",
    },
    header_heading: {
        margin: 0,
        fontSize: "1.125rem",
        color: "rgb(51, 51, 51);",
    },
    header_button: {
        display: "flex",
        alignItems: "center",
        height: "40px",
        padding: "0px 20px",
        background: "#ee4d2d",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 9%)",
        borderRadius: "2px",
        border: "none",
        color: "#fff",
        cursor: "pointer",
    },
    header_icon: {
        fontSize: "24px",
        marginRight: "4px",
    },
    payment_body: {
        color: "rgb(85, 85, 85)",
        fontSize: "20px",
        padding: "90px 0px",
        textAlign: "center",
        width: "100%",
    },  
    paper: {
        overflow: "auto",
        backgroundColor: "rgb(255, 255, 255)",
        boxShadow: "rgb(0 0 0 / 14%) 0px 3px 10px",
        border: "none",
        borderRadius: "3px",
        maxHeight: "88vh",
    },
    payment_channel: {
        display: "flex",
        flexDirection: "column",
    },
    payment_heading: {
        height: "4.5rem",
        fontSize: "22px",
        padding: "0",
        lineHeight: "4.5rem",
    },
    security: {
        padding: "12px",
        background: "rgb(250, 253, 247)",
        display: "flex",
        border: "1px solid rgba(87, 172, 3, 0.3)",
        borderRadius: "2px",
        marginBottom: "12px",
    },
    security_icon: {
        fontSize: "18px",
        marginRight: "12px",
        color: "rgba(85, 158, 14, 1)",
    },
    security_text__up: {
        fontSize: "16px",
        marginBottom: "5px",
        color: "#000",
    },
    security_text__down: {
        color: "rgb(146, 146, 146)",
        fontSize: "14px",
    },
    block_title: {
        height: "42px",
        lineHeight: "42px",
        fontSize: "18px",
        fontWeight: "500",
        color: "rgb(117, 117, 117)",
    },
    inputs: {
        display: "flex",
        width: "100%",
        justifyContent: "center",
    },
    block_input__wrap: {
        margin: "0 0 15px",
        padding: "0px 12px",
        height: "46px",
        border: "1px solid rgb(178, 178, 178, 1)",
        borderRadius: "3px",
        alignItems: "center",
        display: "flex",
        flex: "1",
    },
    wrap_left: {
        marginRight: "5px",
    },
    wrap_right: {
        marginLeft: "5px",
    },
    block_input: {
        width: "100%",
        border: "0px none",
        outline: "none",
        background: "transparent",  
        fontSize: "14px",
    },
    credit: {
        display: "flex",
    },
    credit_input: {
        flex: "1",
    },
    credit_list: {
        display: "flex",
    },
    credit_item: {
        filter: "grayscale(100%)",
        borderRadius: "3px",
        width: "58px",
        height: "48px",
        marginLeft: "10px",
        backgroundPosition: "center center",
        backgroundRepeat: "no-repeat",
        backgroundSize: "90%",
        border: "1px solid rgba(178, 178, 178, 1)",
    },
    credit_item__visa: {
        backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/paymentfe/037611acbdb4a7c5a2363ca313c57bef.png)",
    },
    credit_item__round: {
        backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/paymentfe/05e180f337b0e466235e737ceacdaff4.png)",
    },
    credit_item__jcb: {
        backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/paymentfe/758577188827efdca9bfe95af5873c16.png)",
    },
    credit_item__express: {
        backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/paymentfe/7a66aab4537199ef05393666a472fc58.png)",
    },
    block_buttons: {
        display: "flex",
        marginTop: "40px",
        justifyContent: "flex-end",
        padding: "8px",
        alignItems: "center",
    },
    button_back: {
        outline: "none",
        background: "#ee4d2d",
        padding: "12px 20px",
        border: "0px",
        color: "#fff",
        borderRadius: "2px",
        fontSize: "16px",
        cursor: "pointer",
        marginRight: "20px",
    },
    button_submit: {
        background: "rgba(0, 0, 0, 0.09)",
        color: "rgba(0, 0, 0, 0.26)",
        border: "0px",
        borderRadius: "2px",
        fontSize: "16px",
        padding: "12px 40px",    
    },
    button_complete: {
        marginRight: "0",
        background: "#facac0",
    },
});

export default styles;