const styles = (theme) => ({
    content_navbar: {
        background: "rgba(0,0,0,.03)",
        padding: ".8125rem 1.25rem",
        borderRadius: "2px",
        display: "flex",
        alignItems: "center",
        marginBottom: "0.8rem",
    },
    navbar_label: {
        color: "#555",
        margin: "0 .3125rem 0 0",
    },
    navbar_options: {
        display: "flex",
        alignItems: "center",
        fontSize: "14px",
        color: "rgba(0, 0, 0, 0.8)",
        flex: "1",
    },
    options_item: {
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 2%)",
        height: "2.125rem",
        lineHeight: "2.125rem",
        borderRadius: "2px",
        border: "0",
        backgroundColor: "#fff",
        cursor: "pointer",
        padding: "0 .9375rem",
        marginLeft: ".625rem",
        boxSizing: "border-box",
    },
    options_active: {
        color: "#fff",
        background: "#ee4d2d",
    },
    options_price: {
        marginLeft: ".625rem",
        minWidth: "12.5rem",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 2%)",
        height: "2.125rem",
        lineHeight: "2.125rem",
        borderRadius: "2px",
        border: "0",
        background: "#fff",
        cursor: "pointer",
        boxSizing: "border-box",
        display: "flex",
        alignItems: "center",
        position: "relative",
        "&:hover $price_select": {
            display: "block",
        },
    },
    price_placeholder: {
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        color: "rgba(0,0,0,.8)",
        margin: "0 .625rem 0 .75rem",
        padding: "0",
        width: "100%",
        height: "100%",
    },
    price_icon: {
        width: "40px",
        height: "20px",
    },
    navbar_controls: {
        display: "flex",
        alignItems: "center",
        fontSize: "14px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    controls_state: {
        marginRight: "1.25rem",
    },
    controls_state__current: {
        color: "#ee4d2d",
    },
    control_btn: {
        backgroundColor: "#f9f9f9",
        borderTopRightRadius: "0",
        borderBottomRightRadius: "0",
        borderRight: "1px solid #f2f2f2",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 5%)",
        width: "2.25rem",
        height: "2.125rem",
        borderRadius: "2px",
        border: "0",
        color: "rgba(0,0,0,.26)",
        cursor: "pointer",
    },
    prev_icon: {
        width: "20px",
        height: "20px",
        color: "#ccc",
        marginTop: "4px",
    },
    next_icon: {
        marginTop: "4px",   
        width: "20px",
        height: "20px",
        color: "#555",
    },
    price_select: {
        position: "absolute",
        top: "calc(100% + 1px)",
        left: "0",
        width: "100%",
        right: "0",
        backgroundColor: "#fff",
        zIndex: "1",
        borderRadius: "2px",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 2%)",
        padding: "8px 12px",
        display: "none",
    },
    price_select__item: {
        "&:hover": {
            color: "#ee4d2d",
        },
    },
});

export default styles;