const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "1.25rem 0 3.125rem",
        display: "flex",
    },
    content: {
        width: "980px",
        background: "#fff",
        boxShadow: "0 1px 2px 0 rgb(0 0 0 / 13%)",
        borderRadius: ".125rem",
        marginLeft: "1.6875rem",
        padding: "1.5625rem 2rem",
    },
    content_header: {
        display: "flex",
        alignItems: "center",
    },
    header_left: {
        flex: "1",
        color: "rgba(0, 0, 0, 0.8)",
        fontSize: "1.25rem",
    },
    right_item: {
        textDecoration: "none",
        borderRight: '0.5px solid rgba(0, 0, 0, 0.26)',
        paddingRight: "0.625rem",
        marginLeft: "0.625rem",
        color: "rgb(238, 77, 45)",
        fontSize: "14px",
    },
    right_item__end: {
        color: "#757575",
        borderRight: "none",
    },
    search_voucher: {
        background: "rgba(0, 0, 0, 0.03)",
        padding: "1.75rem 2.75rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        marginTop: "1.25rem",
    },
    search_left: {
        color: "rgba(0, 0, 0, 0.87)",
        fontSize: "16px",
    },
    search_center: {
        margin: "0px 0.5rem 0px 0.875rem",
        width: "25.875rem",
        height: "2.75rem",
        padding: "0.8125rem",
        border: "1px solid rgba(0, 0, 0, 0.14)",
        boxShadow: "rgb(0 0 0 / 2%) 0px 2px 0px 0px inset",
        display: "flex",
        alignItems: "center",
        backgroundColor: "rgb(255, 255, 255)",
        position: "relative",
        borderRadius: "2px",
    },
    search_input: {
        flex: "1 1 0%",
        fontSize: "14px",
        background: "transparent",
        outline: "none",
        boxShadow: "none",
        border: "0px",
    },
    search_button: {
        background: "rgba(0, 0, 0, 0.1)",
        cursor: "default",
        width: "6.25rem",
        height: "2.75rem",
        textAlign: "center",
        borderRadius: "0.125rem",
        outline: "none",
        color: "rgb(255, 255, 255)",
        border: "0px",
        boxShadow: "rgb(0 0 0 / 9%) 0px 1px 1px 0px",
        justifyContent: "center",
        alignItems: "center",
        display: "flex",
    },
});

export default styles;