const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "1.25rem 0 3.125rem",
        display: "flex",
    },
    content: {
        background: "#fff",
        boxShadow: "0 1px 2px 0 rgb(0 0 0 / 13%)",
        borderRadius: ".125rem",
        marginLeft: "1.6875rem",
        padding: "0 1.875rem .625rem",
        width: "980px",
    },
    header: {
        borderBottom: ".0625rem solid #efefef",
        padding: "1.125rem 0",
        height: "80px",
        boxSizing: "border-box",
        alignItems: "center",
        display: "flex",
        justifyContent: "space-between",
    },
    header_heading: {
        margin: 0,
        fontSize: "1.125rem",
        color: "rgb(51, 51, 51);",
    },
    header_button: {
        display: "flex",
        alignItems: "center",
        height: "40px",
        padding: "0px 20px",
        background: "#ee4d2d",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 9%)",
        borderRadius: "2px",
        border: "none",
        color: "#fff",
        cursor: "pointer",
    },
    header_icon: {
        fontSize: "24px",
        marginRight: "4px",
    },
    payment_body: {
        color: "rgb(85, 85, 85)",
        fontSize: "20px",
        padding: "90px 0px",
        textAlign: "center",
        width: "100%",
    },
    paper: {
        overflow: "auto",
        backgroundColor: "rgb(255, 255, 255)",
        boxShadow: "rgb(0 0 0 / 14%) 0px 3px 10px",
        border: "none",
        borderRadius: "3px",
        maxHeight: "88vh",
    },
    payment_channel: {
        display: "flex",
        flexDirection: "column",
    },
    payment_heading: {
        height: "4.5rem",
        fontSize: "22px",
        padding: "0",
        lineHeight: "4.5rem",
    },
    inputs: {
        display: "flex",
        width: "100%",
        justifyContent: "center",
    },
    block_input__wrap: {
        margin: "0 0 15px",
        padding: "0px 12px",
        height: "46px",
        border: "1px solid rgb(178, 178, 178, 1)",
        borderRadius: "3px",
        alignItems: "center",
        display: "flex",
        flex: "1",
    },
    wrap_left: {
        marginRight: "5px",
    },
    wrap_right: {
        marginLeft: "5px",
    },
    block_input: {
        width: "100%",
        border: "0px none",
        outline: "none",
        background: "transparent",  
        fontSize: "14px",
    },
    button_address: {
        outline: "none",
        background: "#fff",
        padding: "10px 12px",
        color: "#757575",
        fontSize: "15px",
        cursor: "pointer",
        margin: "10px 10px 0 0",
        boxSizing: "border-box",
        border: "1px solid rgba(0, 0, 0, 0.09)",
        boxShadow: "rgb(0 0 0 / 3%) 0px 1px 1px",
        borderRadius: "2px",
        "&:focus": {
            color: "rgb(238, 77, 45)",
            borderColor: "rgb(238, 77, 45)",
        },
    },
    address_checkbox__wrap: {
        display: "flex",
        alignItems: "center",
        margin: "20px 0 0",
        opacity: "0.16",
    },
    address_checkbox: {
        backgroundColor: "#f5f5f5",
        color: "#fff",
        cursor: "no-drop",
        height: "15px",
        width: "15px",
        marginRight: "10px",
    },
    block_buttons: {
        display: "flex",
        marginTop: "40px",
        justifyContent: "flex-end",
        padding: "8px",
        alignItems: "center",
    },
    button_back: {
        outline: "none",
        background: "#ee4d2d",
        padding: "12px 20px",
        border: "0px",
        color: "#fff",
        borderRadius: "2px",
        fontSize: "16px",
        cursor: "pointer",
        marginRight: "20px",
    },
    button_submit: {
        background: "#facac0",
        color: "#fff",
        border: "0px",
        borderRadius: "2px",
        fontSize: "16px",
        padding: "12px 30px", 
        cursor: "not-allowed",   
    },
    map_address__wrap: {
        width: "440px",
        height: "120px",
        position: "relative",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: "10px",
    },
    map_address: {
        background: "rgba(207,210,217,.16)",
    },
    map_address__button: {
        position: "absolute",
        padding: "8px 12px",
        color: "#ccc",
        border: "1px solid rgba(0,0,0,.09)",
        background: "#fff",
    },
});

export default styles;