const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "1.25rem 0 3.125rem",
        display: "flex",
    },
    content: {
        width: "980px",
        background: "#fff",
        boxShadow: "0 1px 2px 0 rgb(0 0 0 / 13%)",
        borderRadius: ".125rem",
        marginLeft: "1.6875rem",
        padding: "0 1.875rem .625rem",
    },
    header: {
        borderBottom: ".0625rem solid #efefef",
        padding: "1.125rem 0",
        height: "80px",
        boxSizing: "border-box",
    },
    header_heading: {
        margin: 0,
        fontSize: "1.125rem",
        fontWeight: "500",
        color: "#333",
    },
    header_description: {
        color: "#555",
        marginTop: ".1875rem",
    },
    body: {
        paddingTop: "1.875rem",
        display: "flex",
    },
    body_left: {
        flex: "1",
        paddingRight: "3.125rem",
    },
    field_wrap: {
        marginBottom: "1.875rem",
    },
    field: {
        display: "flex",
        alignItems: "center",
        justifyContent: "flex-start",
    },
    field_title: {
        width: "20%",
        textAlign: "right",
        color: "rgba(85,85,85,.8)",
        marginRight: "1.25rem",
    },
    field_input__wrap: {
        width: "80%",
        boxSizing: "border-box",
        backgroundColor: "#fff",
        borderRadius: "2px",
        border: "1px solid rgba(0,0,0,.14)",
        boxShadow: "inset 0 2px 0 0 rgb(0 0 0 / 2%)",
        height: "40px",
        padding: "10px",
        display: "flex",
        alignItems: "center",
    },
    field_input: {
        flex: "1",
        fontSize: "14px",
        background: "transparent",
        outline: "none",
        boxShadow: "none",
        border: "0",
        color: "#000",
    },
    field_note: {
        width: "100%",
        display: "flex",
        justifyContent: "center",
        marginTop: ".3125rem",
        color: "rgba(0,0,0,.4)",
        paddingLeft: "1.25rem",
        padding: "0 100px 0 0",
        fontSize: "13px",
    },
    field_email__wrap: {
        display: "flex",
    },
    field_email: {
        marginRight: "8px",
    },
    field_button: {
        border: "0",
        outline: "none",
        background: "none",
        color: "#05a",
        fontSize: "14px",
        textDecoration: "underline",
        cursor: "pointer",
    },
    field_button__link: {
        color: "#05a",
    },
    field_radios: {
        display: "flex",
    },
    field_radio: {
        alignItems: "center",
        display: "flex",
        marginRight: "18px",
    },
    radio_label: {
        cursor: "pointer",
    },
    field_radio__input: {
        cursor: "pointer",
        margin: "0 6px 0 0",
        width: "18px",
        height: "18px",
        border: "none",
        outline: "none",
    },
    field_selects: {
        display: "flex",
        flex: "1",
        justifyContent: "space-between",
    },  
    button_save__wrap: {
        marginBottom: "3.75rem",
        paddingLeft: "calc(20% + 1.25rem)",
    },
    button_save: {
        height: "40px",
        padding: "10px 20px",
        minWidth: "70px",
        maxWidth: "220px",
        color: "#fff",
        background: "#ee4d2d",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 9%)",
        borderRadius: "2px",
        cursor: "pointer",
        border: "none",
    },
    body_right: {
        width: "17.5rem",
    },  
    right: {
        borderLeft: ".0625rem solid #efefef",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    right_img__wrap: {
        height: "6.25rem",
        width: "6.25rem",
        margin: "1.25rem 0",
    },
    right_img: {
        backgroundImage: "url(https://cf.shopee.vn/file/a5a4753c0dfe674c5991773369e6dfb0)",
        borderRadius: "50%",
        width: "100%",
        height: "100%",
        backgroundPosition: "50%",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        cursor: "pointer",
    },
    right_input: {
        opacity: "0",
        position: "absolute",
        top: "0%",
        right: "-20%",
        padding: "80px 50px",
        cursor: "pointer",
    },
    right_button: {
        background: "#fff",
        color: "#555",
        border: "1px solid rgba(0,0,0,.09)",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 3%)",
        height: "40px",
        padding: "0 20px",
        minWidth: "70px",
        maxWidth: "220px",
        borderRadius: "2px",
        cursor: "pointer",
        outline: "none",
    },
    view: {
        marginTop: ".75rem",
        display: "flex",
        flexDirection: "column",
    },
    view_text: {
        color: "rgba(0,0,0,.4)",
    },
    margin: {
        float: "right",
    },
    paper: {
        borderRadius: "3px",
        boxShadow: "0 2px 4px rgb(0 0 0 / 50%)",
        border: "none",
        outline: "none",
    },
    paper_header: {
        marginTop: "10px",
        display: "flex",
        alignItems: "center",
        marginBottom: "30px",
    },
    paper_icon: {
        fontSize: "28px",
        color: "#ee4d2d",
        marginRight: "10px",
    },
    paper_title: {
        margin: "0",
        fontSize: "20px",
        color: "#333",
    },
    paper_description: {
        fontSize: "18px",
        color: "#555",
    },
    paper_button: {
        width: "6.25rem",
        minHeight: "2.5rem",
        fontSize: ".875rem",
        textTransform: "uppercase",
        margin: "25px 0 20px 0",
        float: "right",
        color: "#fff",
        background: "#ee4d2d",
        border: "none",
        borderRadius: "2px",
        cursor: "pointer",
    },
    save_wrap: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
    },
    save_icon: {
        color: "rgba(85, 158, 14, 1)",
        fontSize: "60px",
        margin: "15px 0",
    },
    save_text: {
        fontSize: "18px",
        marginBottom: "15px",
    },
});

export default styles;