const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
    },
    content: {
        padding: "0 0 60px",
    },
    counter: {
        padding: "20px 0 0"
    },
    counter_suggestion: {
        backgroundColor: "rgb(255, 254, 251)",
        border: "1px solid rgba(224, 168, 0, 0.4)",
        padding: "0.75rem 1rem",
        display: "flex",
        alignItems: "center",
        marginBottom: "0.625rem",
        borderRadius: "2px",
    },
    counter_suggestion__text: {
        color: "rgb(34, 34, 34)",
        marginLeft: "0.5rem",
        fontSize: "14px",
    },
    counter_category: {
        display: "flex",
        alignItems: "center",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 5%)",
        borderRadius: "3px",
        height: "55px",
        background: "#fff",
        textTransform: "capitalize",
        padding: "0 20px",
    },
    cart_item: {
        marginTop: "12px",
        background: "#fff",
    },
    counter_input__wrap: {
        padding: "0px 12px 0px 20px",
        minWidth: "58px",
        flexDirection: "row-reverse",
        boxSizing: "border-box",
        "&:focus-within $counter_input__check": {
            background: "rgb(238, 77, 45)",
            borderColor: "rgb(238, 77, 45)",
        },
    },
    counter_input__label: {
        display: "flex",
        alignItems: "center",
        cursor: "default",
        position: "relative",
        color: "rgba(0, 0, 0, 0.54)",
        maxWidth: "400px",
    },
    counter_input: {
        boxSizing: "border-box",
        padding: "0",
        top: "0px",
        left: "0px",
        position: "absolute",
    },
    counter_input__check: {
        background: "#fff",
        position: "relative",
        width: "16px",
        height: "16px",
        borderRadius: "2px",
        border: "1px solid rgba(0, 0, 0, 0.14)",
        textAlign: "center",
        boxShadow: "rgb(0 0 0 / 2%) 0px 2px 0px 0px inset",
        marginRight: "8px",
    },
    counter_input__tick: {
        borderColor: "rgb(255, 255, 255)",
        position: "absolute",
        height: "5px",
        width: "9px",
        borderLeft: "2px solid rgb(255, 255, 255)",
        borderBottom: "2px solid rgb(255, 255, 255)",
        transform: "rotate(-45deg)",
        left: "3px",
        top: "3px",
    },
    counter_category__title: {
        color: "rgba(0,0,0,.8)",
        width: "46.27949%",
        fontSize: "14px",
    },
    counter_category__item: {
        color: "#888",
        fontSize: "14px",
        textAlign: "center",
        width: "15.88022%",
    },
    cart_product__store: {
        display: "flex",
        padding: "0 20px",
        height: "3.75rem",
        alignItems: "center",
        borderBottom: "1px solid rgba(0,0,0,.09)",
    },
    counter_store__link: {
        textDecoration: "none", 
        display: "flex",
        alignItems: "center",
    },
    counter_store__text: {
        margin: "0 10px",
        color: "rgba(0,0,0,.87)",
        fontSize: "14px",
        textDecoration: "none",
    },
    cart_item__product: {
        padding: "30px 20px 20px",
        display: "flex",
        alignItems: "center",
    },
    product_detail: {
        width: "29.03811%",
        display: "flex",
    },
    detail_img: {
        backgroundPosition: "50%",
        backgroundSize: "contain",
        backgroundRepeat: "no-repeat",
        width: '80px',
        height: "80px",
    },
    detail_list: {
        padding: "5px 20px 0 10px",
        width: "243.5px",
        display: "flex",
        flexDirection: "column",
    },
    detail_description: {
        textDecoration: "none",
        color: "rgba(0,0,0,.87)",
        display: "-webkit-box",
        marginBottom: "5px",
        maxHeight: "32px",
        textOverflow: "ellipsis",
        wordBreak: "break-word",
        "-webkit-box-orient": "vertical",
        "-webkit-line-clamp": "2",
        lineHeight: "16px",
        overflow: "hidden",
        fontSize: "14px",
    },
    detail_list__img: {
        backgroundImage: "url(https://cf.shopee.vn/file/b8420b9f9230e42af760e3227b4c4fa2)",
        height: "18px",
        backgroundSize: "contain",
        backgroundRepeat: "no-repeat",
    },
    detail_sale: {
        display: "flex",
        marginTop: "4px",
        alignItems: "center",
    },
    detail_sale__img: {
        width: "15.6px",
        height: "14px",
    },
    detail_sale__text: {
        fontSize: "12px",
        color: "#252525",
        marginLeft: "5px",
    },
    product_type: {
        width: "17.24138%",
        color: "rgba(0,0,0,.54)",
        fontSize: ".875rem",
        cursor: "pointer",
        position: "relative",
    },
    product_type__modal: {
        position: "absolute",
        top: "110%",
        right: "-1.25rem",
        padding: "27px 25px",
        width: "364px",
        maxHeight: "28.125rem",
        overflowY: "auto",
        background: "#fff",
        boxShadow: "0 5px 10px 0 rgb(0 0 0 / 9%)",
        borderRadius: ".125rem",
        overflow: "hidden",
        border: "1px solid rgba(0,0,0,.09)",
        whiteSpace: "pre-wrap",
        zIndex: "1",
    },
    type_modal__title: {
        marginBottom: "10px",
        color: "rgba(0,0,0,.54)",
        fontSize: "16px",
    },
    type_modal__item: {
        cursor: "pointer",
        minWidth: "5rem",
        minHeight: "2.125rem",
        boxSizing: "border-box",
        padding: "0.25rem 0.75rem",
        margin: "0px 8px 8px 0px",
        color: "rgba(0, 0, 0, 0.8)",
        textAlign: "left",
        borderRadius: "2px",
        border: "1px solid rgba(0, 0, 0, 0.09)",
        position: "relative",
        background: "rgb(255, 255, 255)",
        outline: "0px",
        wordBreak: "break-word",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
    },
    modal_item__selector: {
        color: "#ee4d2d",
        borderColor: "#ee4d2d",
        "& > $modal_tick": {
            display: "block",
        },
    },
    modal_tick: {
        width: ".9375rem",
        height: ".9375rem",
        position: "absolute",
        overflow: "hidden",
        right: "0",
        bottom: "0",
        "&:after": {
            border: ".9375rem solid transparent",
            borderBottom: ".9375rem solid var(--brand-primary-color,#ee4d2d)",
            content: '""',
            position: "absolute",
            right: "-.9375rem",
            bottom: "0",
        },
        display: "none",
    },
    modal_tick__icon: {
        position: "absolute",
        right: "0",
        bottom: "0",
        color: "#fff",
        fontSize: "10px",
        zIndex: "1",
    },
    modal_buttons: {
        marginTop: "20px",
        justifyContent: "flex-end",
        display: "flex",
        flex: "1",
    },
    modal_button_back: {
        background: "transparent",
        color: "#555",
        marginRight: "10px",
        padding: "8px 36px",
        "&:hover": {
            background: "#f8f8f8",
            color: "#555",
        },
    },
    type_title__wrap: {
        display: "flex",
        alignItems: "center",
    },
    type_icon: {
        marginLeft: "6px",
        fontSize: "20px",
    },
    type_name: {
        textOverflow: "ellipsis",
        overflow: "hidden",
        "word-break": "break-word",
        display: "-webkit-box",
        "-webkit-box-orient": "vertical",
        "-webkit-line-clamp": "2",
        textAlign: "left",
        marginTop: "5px",
    },
    product_price: {
        width: "15.88022%",
        fontSize: "14px",
    },
    price_old: {
        textDecoration: "line-through",
        color: "rgba(0,0,0,.54)",
        marginRight: "10px",
    },
    price_new: {
        color: "#ee4d2d",
    },
    product_quantity: {
        width: "15.4265%",
        display: "flex",
    },
    quantity_input: {
        width: "50px",
        height: "32px",
        borderLeft: "0",
        borderRight: "0",
        textAlign: "center",
        cursor: "text",
        borderRadius: "0",
        "-webkit-appearance": "none",
        outline: "none",
        border: "1px solid rgba(0,0,0,.09)",
        fontSize: "16px",
        color: "rgba(0,0,0,.87)",
    },
    quantity_button: {
        border: "1px solid rgba(0,0,0,.09)",
        borderRadius: "2px",
        width: "32px",
        height: "32px",
        backgroundColor: "transparent",
        fontSize: "20px",
        color: "rgba(0,0,0,.54)",
        cursor: "pointer"
    },
    product_price__total: {
        width: "10.43557%",
        textAlign: "right",
        color: "#ee4d2d",
        fontSize: "14px",
        paddingRight: "16px",
    },
    product_similar: {
        width: "12.70417%",
        alignItems: "center",
        display: "flex",
        flexDirection: "column",
    },
    similar_delete: {
        cursor: "pointer",
        background: "none",
        border: "0",
        color: "rgba(0,0,0,.95)",
        "&:hover": {
            color: "#ee4d2d",
        }
    },
    similar_search: {
        cursor: "pointer",
        padding: "0.8rem 0.4375rem",
        color: "rgba(0, 0, 0, 0.7)",
        backgroundColor: "transparent",
        border: "none",
        display: "flex",
        "&:hover": {
            color: "#ee4d2d",
        }
    },
    similar_icon: {
        fontSize: "20px",
    },
    cart_item_service: {
        alignItems: "center",
        padding: "1.25rem 0 1.25rem 2.5rem",
        borderTop: "1px solid rgba(0,0,0,.09)",
        display: "flex",
        fontSize: "14px",
    },
    service_text: {
        marginLeft: "0.9375rem",
        color: "rgba(0,0,0,.8)",
    },
    drawer: {
        position: "relative",
        display: "flex",
        justifyContent: "center",
        "&::after": {
            position: "absolute",
            bottom: "-10px",
            left: "50%",
            transform: "translateX(-50%)",
            backgroundColor: "transparent",
            width: "100%",
            height: "20px",
            display: "block",
            content: '""',
        },
        "&:hover $drawer_detail": {
            display: "flex",
        },
    },
    drawer_text: {
        marginLeft: ".375rem",
        color: "#05a",
        cursor: "pointer",
    },
    drawer_detail: {
        display: "none",
        position: "absolute",
        top: "24px",
        left: "50%",
        transform: "translateX(-50%)",
        background: "#fff",
        flexDirection: "column",
        zIndex: "1",
        border: "1px solid rgba(0,0,0,.09)",
        boxShadow: "0 1px 3.125rem 0 rgb(0 0 0 / 40%)",
        borderRadius: "4px",
        animation: "all linear 0.3s",
        padding: "20px",
        width: "500px",
    },
    drawer_detail__heading: {
        fontSize: "20px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    drawer_detail__name: {
        fontSize: "16px",
        color: "rgba(0, 0, 0, 0.3)",
        fontWeight: "500",
    },
    drawer_column__category: {
        fontSize: "17px",
        color: "rgba(0, 0, 0, 0.46)",
        margin: "16px 0 0",
        minHeight: "40px",
        fontWeight: "500",
    },
    drawer_column__value: {
        fontSize: "16px",
        color: "rgba(0, 0, 0, 0.8)",
        margin: "16px 0 0",
    },
    pay: {
        backgroundColor: "#fff",
        margin: "20px 0 40px",
        // position: "sticky",
        bottom: "0",
    },
    pay_up: {
        borderBottom: "1px dashed rgba(0,0,0,.09)",
    },
    pay_up__right: {
        padding: "0.75rem 1.875rem 0.75rem 0",
        display: "flex",
        alignItems: "center",
    },
    pay_up__icon: {
        color: "#ee4d2d",
        width: "1.3125",
        height: "1.25rem",
        margin: "0 .3125rem",
    },
    pay_up__title: {
        color: "rgba(0,0,0,.8)",
        flex: "1",
        fontSize: "16px",
    },
    pay_up__button: {
        color: "#ee4d2d",
        fontSize: "14px",
        background: "transparent",
        border: "none",
        cursor: "pointer",
    },
    pay_center: {
        opacity: "0.4",
    },
    pay_center__right: {
        display: "flex",
        alignItems: "center",
    },
    pay_center__xu: {
        color: "orange",
        height: "18px",
        width: "18px",
    },
    right_wrap: {
        display: "flex",
        flex: "1",
        alignItems: "center",
    },
    pay_center__text: {
        fontSize: "14px",
        marginLeft: "8px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    pay_center__title: {
        marginLeft: "17px",
        fontSize: "14px",
        fontWeight: "500",
    },
    pay_center__help: {
        height: "28px",
        width: "28px",
        color: "rgba(0,0,0,.54)",
        paddingRight: "6px",
        paddingLeft: "6px",
    },
    pay_center__sale: {
        fontSize: "14px",
        paddingRight: "30px",
    },
    pay_center__left: {
        padding: "16px 12px 16px 20px",
        justifyContent: "flex-end",
        display: "flex",
    },
    input_wrap__disabled: {
        "&:focus-within $counter_input__check": {
            background: "#e7e7e7",
            borderColor: "#e7e7e7",
        },
    },
    label_disabled: {
        cursor: "no-drop",
    },
    check_disabled: {
        background: "#e7e7e7",
    },
    tick_disabled: {
        border: "transparent",
    },
    pay_down: {
        padding: "12px 0",
        borderTop: "1px dashed rgba(0,0,0,.09)",
        display: "flex",
        justifyContent: "space-between",
    },
    pay_down__left: {
        display: "flex",
        alignItems: "center",
    },
    down_left__button: {
        fontSize: "16px",
        color: "rgba(0, 0, 0, 0.8)",
        border: "0",
        padding: "1px 6px",
        backgroundColor: "transparent",
        margin: "0 4px",
        cursor: "pointer",
    },
    left_save: {
        color: "#ee4d2d",
        margin: "0 8px",
        maxWidth: "168px",
        whiteSpace: "nowrap",
        overflow: "hidden",
        textOverflow: "ellipsis",
        "-webkit-appearance": "button",
    },
    pay_down__right: {
        display: "flex",
        alignItems: "center",
    },
    down_right__price: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
    },
    right_price__up: {
        display: "flex",
        alignItems: "center",
    },
    down_right__title: {
        color: "#222",
    },
    down_right__total: {
        marginLeft: "5px",
        fontSize: "24px",
        color: "#ee4d2d",
    },
    down_right__buy: {
        margin: "0 22px 0 15px",
        padding: "12px 36px",
        width: "13.125rem",
        fontSize: "14px",
        textAlign: "center",
        backgroundColor: "#ee4d2d",
        border: "0",
        borderRadius: "2px",
        color: "#fff",
        cursor: "pointer",
        outline: "0",
        "&:hover": {
            opacity: "0.9",
        },
    },
    right_price__down: {
        display: "flex",
        alignItems: "center",
        width: "100%",
        justifyContent: "flex-end",
        fontSize: "14px",
    },
    price_down__value: {
        paddingLeft: "24px",
        color: "#ee4d2d",
    },
    mall_wrap: {
        backgroundColor: "#d0011b",
        borderRadius: "2px",
        padding: "0 3px",
    },
    cart_empty: {
        padding: "20px",
    },
    cart_empty__heading: {
        marginTop: "2.5rem",
        color: "rgba(0, 0, 0, 0.8)",
    },
    cart_empty__button: {
        marginTop: "6.25rem",
        width: "100%",
        padding: "0.75rem 0",
        backgroundColor: "#ee4d2d",
        color: "#fff",
        outline: "0",
        border: "0",
        borderRadius: "3px",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 9%)",
        cursor: "pointer",
    },
    toast: {
        position: "fixed",
        top: "50%",
        left: "50%",
        transform: "translate(-50%, -50%)",
        backgroundColor: "rgba(0, 0, 0, 0.65)",
        color: "#fff",
        padding: "15px",
        justifyContent: "space-around",
        borderRadius: "7px",
        flexDirection: "column",
        alignItems: "center",
        textAlign: "center",
    },
    toast_text: {
        marginTop: "7px",
        fontSize: "14px",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        boxSizing: "border-box",
        padding: "30px 30px 0",
        overflow: "hidden",
        maxHeight: "620px",
    },
    form_header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: "1.25rem",
    },
    header_help: {
        display: "flex",
        alignItems: "center",
        fontSize: "14px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    header_help__icon: {
        fontSize: "14px",
        marginLeft: "4px",
    },
    header_heading: {
        color: "rgb(34, 34, 34)",
        fontSize: "1.25rem",
    },
    form_search: {
        display: "flex",
        padding: "0.9375rem",
        alignItems: "center",
        background: "rgb(248, 248, 248)",
        fontSize: "14px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    search_center: {
        flex: "1 1 0",
        marginLeft: "0.6875rem",
        display: "flex",
        alignItems: "center",
        backgroundColor: "rgb(255, 255, 255)",
        position: "relative",
        borderRadius: "2px",
        border: "1px solid rgba(0, 0, 0, 0.14)",
        boxSizing: "border-box",
        boxShadow: "rgb(0 0 0 / 2%) 0px 2px 0px 0px inset",
        color: "rgb(34, 34, 34)",
        height: "40px",
        padding: "10px",
    },
    search_center__input: {
        background: "transparent",
        width: "100%",
        outline: "none",
        boxShadow: "none",
        border: "0px",
    },
    search_right: {
        color: "rgb(204, 204, 204)",
        backgroundColor: "rgb(255, 255, 255)",
        borderColor: "rgba(0, 0, 0, 0.05)",
        borderRadius: "2px",
        boxShadow: "rgb(0 0 0 / 3%) 0px 1px 1px 0px",
        width: "5.875rem",
        height: "2.5rem",
        marginLeft: "8px",
        fontWeight: "bold",
    },
    form_main: {
        paddingLeft: "0.25rem",
        marginLeft: "-0.25rem",
        boxSizing: "border-box",
        flex: "1 1 0%",
        paddingRight: "50px",
        marginRight: "-50px",
    },
    form_content__wrap: {
        paddingBottom: "5.25rem",
        display: "flex",
        flexDirection: "column",
        height: "100%",
        boxSizing: "border-box",
        margin: "0px",
    },
    form_content: {
        marginLeft: "-0rem",
        marginRight: "-0rem",
        paddingLeft: "0.25rem",
        paddingRight: "1.25rem",
        marginTop: "1.25rem",
        width: "103%",
        boxSizing: "border-box",
        overflowY: "scroll",
        maxHeight: "380px",
    },
    content_note: {
        marginTop: "0.3125rem",
        marginBottom: "0.9375rem",
        padding: "0.625rem 0.9375rem",
        background: "rgb(254, 247, 231)",
        color: "rgba(0, 0, 0, 0.65)",
        fontSize: "0.875rem",
        boxSizing: "border-box",
    },
    content_text: {
        color: "rgba(0, 0, 0, 0.65)",
        marginBottom: "0.625rem",
    },
    voucher_button__back: {
        padding: "8px 36px",
        backgroundColor: "transparent",
        marginRight: "12px",
        border: "0",
        outline: "0",
        borderRadius: "2px",
        cursor: "pointer",
        "&:hover": {
            backgroundColor: "#f8f8f8",
        },
    },
    popup: {
        padding: "1.25rem",
        color: "rgba(0, 0, 0, 0.8)",
    },
    popup_heading: {
        fontSize: "1.5rem",
        color: "#ee4d2d",
        marginTop: "1.875rem",
    },
    popup_message: {
        margin: "2.5rem 0 6.25rem",
    },
    popup_yes: {
        color: "#fff",
        background: "#ee4d2d",
        height: "40px",
        width: "100%",
        border: "0",
        outline: "0",
        borderRadius: "2px",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 9%)",
        cursor: "pointer",
    },
    popup_no: {
        background: "#fff",
        height: "40px",
        width: "100%",
        outline: "0",
        borderRadius: "2px",
        border: "1px solid rgba(0,0,0,.09)",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 3%)", 
        color: "#555",
        cursor: "pointer",
    },
});

export default styles;