const styles = (theme) => ({
    h3: {
        width: "100%",
    },
    container: {
        backgroundColor: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "20px auto 0",
    },
    header: {
        paddingTop: "",
        background: "#fff",
        borderBottom: "1px solid rgba(0,0,0,.05)",
        padding: "15px 20px",
        display: "flex",
        alignItems: "center",
    },
    flash_sale: {
        flex: "1",
    },
    flash_sale__img: {
        paddingLeft: "16px",
        width: "114px",
        height: "30px",
        lineHeight: "30px",
        display: "inline-block",
        background: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/fb1088de81e42c4e538967ec12cb5caa.png) 50% no-repeat",
        backgroundSize: "contain",
    },
    view_all__button: {
        color: "#ee4d2d",
        padding: ".3125rem .4375rem",
        border: "0",
        outline: "none",
        cursor: "pointer",
        fontSize: "0.875rem",
        backgroundColor: "transparent",
    },
    content: {
        backgroundColor: "#fff",
    },
    card_item: {
        boxSizing: "border-box",
        position: "relative",
    },
    card_item__link: {
        width: "173px",
        display: "block",
        margin: "5px auto",
        textDecoration: "none",
    },
    item_img: {
        width: "100%",
        transition: "opacity .2s ease",
        display: "block",
    },
    item_view: {
        padding: "10px 15px 15px",
        textAlign: "center",
    },
    item_price: {
        color: "#ee4d2d",
    },
    item_price__value: {
        fontSize: "155%",
        maxWidth: "130px",
        overflow: "hidden",
        textOverflow: "ellipsis",
    },
    item_quantity__wrap: {
        padding: "0 7px",
        height: "16px",
        background: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/ac7f81d9ee062223753413ec98497a86.png) 0 100% no-repeat",
        backgroundSize: "cover",
        position: "relative",
        borderRadius: "8px",
    },
    item_quantity: {
        fontSize: "12px",
        color: "#fff",
        zIndex: "2",
        position: "absolute",
        bottom: "0",
        width: "100%",
        textAlign: "center",
    },
    label_wrap: {
        transform: "scale(1.4)",
        padding: "7px 8px",
        fontWeight: 400,
        position: "absolute",
        top: "0",
        right: "100%",
        zIndex: "3",
    },
    label: {
        width: "36px",
        height: "32px",
        backgroundColor: "rgba(255,212,36,.9)",
        display: "flex",
        flexDirection: "column",
        padding: "4px 2px 3px",
        boxSizing: "border-box",
        fontSize: "14px",
        textAlign: "center",
        position: "relative",   
    },
    label_percent: {
        color: "#ee4d2d",
        lineHeight: "0.8125rem",
    },
    label_sale: {
        color: "#fff",
        lineHeight: "0.8125rem",
    },
    label_after: {
        width: "0",
        height: "0",
        left: "0",
        bottom: "-4px",
        position: "absolute",
        borderColor: "transparent rgba(255,212,36,.9)",
        borderStyle: "solid",
        borderWidth: "0 18px 4px",
    },
    banner: {
        margin: "20px 0",
        backgroundColor: "#fff",
        display: "flex",
    },
    banner_item: {
        flex: "33.333335%",
        maxWidth: "33.33333%",
    },
    banner_item__link: {
        width: "400px",
        height: "110px",
        borderRadius: "2px",
        textDecoration: "none",
        color: "rgba(0,0,0,.8)",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        backgroundPosition: "50%",
        display: "block",
    },
    banner_sale: {
        backgroundImage: "url(https://cf.shopee.vn/file/0d3760c72e291ef1c27af38edc87d392)",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        height: "100%",
    },
    banner_event: {
        backgroundImage: "url(https://cf.shopee.vn/file/34347993efd45a40f89cbf4d68933f8f)",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        height: "100%",
    },
    banner_support: {
        backgroundImage: "url(https://cf.shopee.vn/file/0ed04e926f31502f845ab60311fafd7d)",
        backgroundSize: "cover",
        backgroundRepeat: "no-repeat",
        height: "100%",
    },
});

export default styles;