const styles = (theme) => ({
    container: {
        background: "#f5f5f5",
    },
    wide: {
        maxWidth: "1200px",
        margin: "0 auto",
        padding: "1.25rem 0 3.125rem",
        display: "flex",
    },
    content: {
        width: "100%",
    },
    tabs_category: {
        width: "1200px",
        margin: "0 auto",
    },
    voucher_store: {
        width: "100%",
        boxShadow: "0 1px 1px 0 rgb(0 0 0 / 5%)",
        borderRadius: ".125rem",
        background: "#fff",
        margin: ".625rem 0",
        padding: "1.25rem 1.875rem",
    },
    voucher_heading: {
        fontWeight: "400",
        fontSize: "16px",
        marginBottom: "16px",
        color: "rgba(0, 0, 0, 0.8)",
    },
    voucher_item: {
        height: "6.75rem",
        boxShadow: "0.125rem 0.125rem 0.3125rem rgb(0 0 0 / 7%)",
        borderRadius: ".125rem",
        display: "flex",
        alignItems: "center",
        position: "relative",
        boxSizing: "border-box",
        marginRight: "20px",
    },
    voucher_item__dash: {
        borderTop: "1px solid #fbc9c0",
        borderBottom: "1px solid #fbc9c0",
        background: "linear-gradient(to right, transparent 0 .25rem, #fff4f4 .25rem)",
        minWidth: ".3125rem",
        marginLeft: "1px",
        borderRadius: ".1875rem 0 0 .1875rem",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        position: "absolute",
        height: "100%",
    },
    dash_block: {
        top: "0",
        left: "0",
        position: "absolute",
        width: ".3125rem",
        height: "100%",
    },
    dash_wrap: {
        background: "radial-gradient(circle at 0 .375rem, transparent 0, rgba(0,0,0,0.03) .1875rem, #fbc9c0 .1875rem, #fbc9c0 .25rem, #fff4f4 .25rem)",
        backgroundSize: ".25rem .625rem",
        backgroundRepeat: "repeat-y",
        position: "absolute",
        top: "0",
        left: "0",
        width: ".25rem",
        height: "100%",
    },
    dash_child: {
        background: "repeating-linear-gradient(#fbc9c0, #fbc9c0 .1875rem, transparent .1875rem, transparent .625rem)",
        backgroundSize: "1px .625rem",
        position: "absolute",
        top: "0",
        left: "0",
        height: "100%",
        width: "1px",
    },
    voucher_item__detail: {
        display: "flex",
        alignItems: "center",
        flex: "1",
        height: "100%",
        background: "#fff4f4",
        border: "1px solid #fbc9c0",
        borderLeft: "0 solid transparent",
        paddingLeft: "1.6rem",
        borderRadius: "0 .125rem .125rem 0",
    },
    detail_left__wrap: {
        height: "100%",
        position: "relative",
        flex: "1",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
    },
    detail_left: {
        paddingRight: "1.4rem",
    },
    left_highlight: {
        color: "#ee4d2d",
        fontSize: "0.875rem",
        overflow: "hidden",
        display: "-webkit-box",
        textOverflow: "ellipsis",
        "-webkit-box-orient": "vertical",
        "-webkit-line-clamp": "2",
        lineHeight: "1rem",
        maxHeight: "2.0625rem",
    },
    left_expired: {
        fontSize: "12px",
        color: "rgba(0, 0, 0, 0.54)",
    },
    left_dash: {
        position: "absolute",
        top: "0",
        right: "0",
        width: "1px",
        height: "100%",
        background: "repeating-linear-gradient(#e8e8e8, #e8e8e8 .125rem, transparent .125rem .25rem)",
        backgroundSize: "1px .25rem",
        backgroundRepeat: "repeat-y",
    },
    right_button: {
        height: "1.75rem",
        padding: "0 .5625rem",
        width: "3.4375rem",
        margin: "0 .875rem",
        backgroundColor: "#ee4d2d",
        color: "#fff",
        borderRadius: "2px",
        cursor: "pointer",
        border: "none",
        outline: "0",
    },
    hot_sold__heading: {
        fontSize: "1rem",
        color: "rgba(0,0,0,0.54)",
        fontWeight: "500",
        padding: "1.25rem 0 0.625rem",
    },
    products_store: {
        margin: "1.875rem 0 5rem",
    },
    navbar_heading: {
        display: "flex",
        alignItems: "center",
        fontSize: "1rem",
        fontWeight: "500",
        borderBottom: "1px solid rgba(0,0,0,0.05)",
        marginBottom: "0.625rem",
        padding: "16px 0",
    },
    navbar_heading__icon: {
        fontSize: "18px",
        marginRight: "10px",
    },
    navbar_category__item: {
        display: "flex",
        alignItems: "center",
        fontSize: "14px",
        padding: "8px 16px", 
    },
    category_item__icon: {
        fontSize: "18px",
    },
    category_item__active: {
        color: "#ee4d2d",
        padding: "8px 0",
    },
});

export default styles;