const styles = (theme) => ({
	link: {
		textDecoration: "none",
		padding: "0 2px",
		display: "block",
		"&:hover": {
			transform: "translateY(-2px)",
		},
		transition: "all linear 0.2s",
	},
	card: {
		maxWidth: 300,
		margin: "2px auto",
		transition: "0.3s",
		boxShadow: "0 8px 40px -12px rgba(0,0,0,0.3)",
		"&:hover": {
			boxShadow: "0 16px 70px -12.125px rgba(0,0,0,0.3)",
		},
		position: "relative",
		overflow: "unset",
	},
	media: {
		paddingTop: "100%",
		position: "relative",
	},
	content: {
		padding: "10px !important ",
	},
	divider: {
		margin: "10px",
	},
	subheading: {
		lineHeight: 1.8,
	},
	avatar: {
		display: "inline-block",
		border: "2px solid white",
		"&:not(:first-of-type)": {
			marginLeft: "10px",
		},
	},
	heading: {
		fontSize: "16px",
		fontWeight: "400",
		color: "#222222",
		lineHeight: "1.8rem",
		overflow: "hidden",
		margin: "8px",
		textDecoration: "none",
		display: "-webkit-box",
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: "2",
	},
	caption: {
		fontSize: "14px",
		lineHeight: "18px",
		fontWeight: "400",
		color: "#222222",
		wordWrap: "break-word",
		overflow: "hidden",
		display: "-webkit-box",
		textOverflow: "ellipsis",
		"-webkit-box-orient": "vertical",
		"-webkit-line-clamp": "2",
	},
	bill: {
		display: "flex",
		marginTop: "4px",
		justifyContent: "space-between",
	},
	tag: {
		color: "white",
		backgroundColor: "rgb(246, 145, 19)",
		lineHeight: "1rem",
		height: "1rem",
		borderRight: "1px dashed ",
		borderLeft: "1px dashed ",
		textAlign: "center",
		fontSize: "12px",
		padding: "0 4px",
	},
	hashtag: {
		color: "rgb(255, 0, 32)",
		border: "1px solid",
		fontSize: "12px",
		padding: "0 4px",
	},
	price_wrap: {
		display: "flex",
		justifyContent: "space-between",
		alignItems: "center",
	},
	price_old: {
		fontSize: "14px",
		color: "#666",
		textDecoration: "line-through",
		marginRight: "6px",
	},
	price_current: {
		fontSize: "16px",
		color: "#ee4d2d",
	},
	icons: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
	},
	icons_rate: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	loveIcon: {
		margin: "-2px 5px 0 0",
	},
	startIcon: {
		color: "rgb(255, 216, 64, 0.94)",
		fontSize: "12px",
	},
	quantity: {
		color: "#ee4d2d",
	},
	address : {
		textAlign: "right",
		fontSize: "15px",
		color: "rgba(0,0,0,.65);",
		marginTop: "2px",
	},
	mall: {
		position: "absolute",
		left: "-3px",
		top: ".625rem",
		backgroundColor: "rgb(208, 1, 27)",
		fontSize: ".75rem",
		padding: "4px 8px",
		borderTopRightRadius: ".125rem",
		borderBottomRightRadius: ".125rem",
	},
	mall_triangle: {
		display: "inline-block",
		position: "absolute",
		left: "0",
		bottom: "-.1875rem",
		borderTop: ".1875rem solid",
		borderLeft: ".1875rem solid transparent",
		filter: "brightness(60%)",
	},
	mall_img: {
		color: "rgb(208, 1, 27)",
		backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/1ea7594a0e6dbc0cdb8640b83a1079bb.png)",
		backgroundRepeat: "no-repeat",
		backgroundSize: "contain",
		height: ".5rem",
		width: "1.25rem",
		position: "relative",
	},
	label: {
		position: "absolute",
		right: "0",
		top: "0",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		padding: "4px 2px 3px",
		backgroundColor: "rgba(255,212,36,.9)",
		width: "40px",
		height: "40px",
		fontSize: "14px",
	},
	label_percent: {
		color: "#ee3d2d",
	},
	label_sale: {
		color: "#fff",
	},
	label_after: {
		width: "4px",
		height: "0",
		left: "0",
		bottom: "-4px",
		position: "absolute",
		borderColor: "transparent rgba(255,212,36,.9)",
		borderStyle: "solid",
		borderWidth: "0 20px 4px",
	},
	sold_out: {
		zIndex: "2",
		position: "absolute",
		top: "50%",
		left: "50%",
		transform: "translate(-50%, -50%)",
		justifyContent: "center",
		display: "flex",
		alignItems: "center",
		backgroundColor: "rgba(0,0,0,0.65)",
		color: "white",
		textAlign: "center",
		fontSize: ".75rem",
		height: "3.75rem",
		minWidth: "3.875rem",
		borderRadius: "5rem"
	},
});

export default styles;
