const styles = (theme) => ({
    top_search: {
        backgroundColor: "#f5f5f5",
        padding: "20px 0 30px",
        boxSizing: "border-box",
    },
    container: {
        maxWidth: "1200px",
        margin: "0 auto",
    },
    header: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        background: "#fff",
        height: "3.75rem",
        borderBottom: "1px solid rgba(0,0,0,.05)",
        padding: "0 24px",
        color: "#ee4d2d",
    },
    header_link: {
        color: "#ee4d2d",
        textDecoration: "none",
        display: "flex",
        alignItems: "center",
        fontSize: "16px",
    },
    header_icon: {
        fontSize: "20px",
    },
    product_link: {
        textDecoration: "none",
        padding: "1.25rem .625rem",
        display: "block",
        backgroundColor: "#fff",

    },
    product_view: {
        position: "relative",
    },
    product_img__wrap: {
        paddingTop: "100%",
        width: "100%",
    },
    product_img: {
        position: "absolute",
        verticalAlign: "bottom",
        objectFit: "contain",
        width: "100%",
        top: "50%",
        left: "50%",
        maxWidth: "100%",
        transform: "translate(-50%,-50%)",
    },
    product_label: {
        position: "absolute",
        top: "0",
        left: "0",
        zIndex: "1",
        width: "2rem",
        height: "2.5rem",
        backgroundSize: "2rem 2.5rem",
        backgroundRepeat: "no-repeat",
        backgroundImage: "url(https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/06720e49514cbd94b7552496b4de454a.png)",
    },
    product_description: {
        overflow: "hidden",
        display: "-webkit-box",
        textOverflow: "ellipsis",
        "-webkit-box-orient": "vertical",
        "-webkit-line-clamp": "2",
        marginTop: "1.25rem",
        color: "#555",
        fontSize: "1.125rem",
        textAlign: "left",
        textTransform: "capitalize",
        wordBreak: "break-word",
        minHeight: "50px",
        lineHeight: "25px",
        fontWeight: "500",
    },
    product_quantity: {
        bottom: "0",
        left: "0",
        height: "1.5625rem",
        backgroundColor: "rgba(0,0,0,.26)",
        color: "#fff",
        position: "absolute",
        width: "100%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
});

export default styles;